version: "3.9"

services:
  db:
    image: postgres:16
    container_name: geomapa-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geomapa
    volumes:
      - geomapa_db_data:/var/lib/postgresql/data

volumes:
  geomapa_db_data:
